/*
  Simple DirectMedia Layer
 gcc -g -Wall -I"../SDL2/include/" array.c sprite.c matrix.c -lSDL2 -lGL -lm -Ddebug_sprite && ./a.out
  Copyright (C) 1997-2016 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

/* list of OpenGL functions sorted alphabetically
   If you need to use a GL function from the SDL video subsystem,
   change its entry from SDL_PROC_UNUSED to SDL_PROC and rebuild.
*/
#define SDL_PROC_UNUSED(ret,func,params)

SDL_PROC(GLenum, glGetError, (void))
SDL_PROC(const GLubyte *, glGetString, (GLenum name))
SDL_PROC(void, glBegin, (GLenum))
SDL_PROC(void, glBindTexture, (GLenum, GLuint))
SDL_PROC(void, glBlendFunc, (GLenum, GLenum))
SDL_PROC(void, glBlendFuncSeparate, (GLenum, GLenum, GLenum, GLenum))
SDL_PROC(void, glClear, (GLbitfield))
SDL_PROC(void, glClearColor, (GLclampf, GLclampf, GLclampf, GLclampf))
SDL_PROC(void, glColor3f, (GLfloat, GLfloat, GLfloat))
SDL_PROC(void, glColor3fv, (const GLfloat *))
SDL_PROC(void, glColor4f, (GLfloat, GLfloat, GLfloat, GLfloat))
SDL_PROC(void, glDeleteTextures, (GLsizei n, const GLuint * textures))
SDL_PROC(void, glDepthFunc, (GLenum func))
SDL_PROC(void, glDisable, (GLenum cap))
SDL_PROC(void, glDrawPixels, (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels))
SDL_PROC(void, glEnable, (GLenum cap))
SDL_PROC(void, glEnd, (void))
SDL_PROC(void, glGenTextures, (GLsizei n, GLuint * textures))
SDL_PROC(void, glGetIntegerv, (GLenum pname, GLint * params))
SDL_PROC(void, glGetPointerv, (GLenum pname, GLvoid * *params))
SDL_PROC(void, glLineWidth, (GLfloat width))
SDL_PROC(void, glLoadIdentity, (void))
SDL_PROC(void, glMatrixMode, (GLenum mode))
SDL_PROC(void, glOrtho, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
SDL_PROC(void, glPixelStorei, (GLenum pname, GLint param))
SDL_PROC(void, glPointSize, (GLfloat size))
SDL_PROC(void, glPopMatrix, (void))
SDL_PROC(void, glPushMatrix, (void))
SDL_PROC(void, glRasterPos2i, (GLint x, GLint y))
SDL_PROC(void, glReadBuffer, (GLenum mode))
SDL_PROC(void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels))
SDL_PROC(void, glRectf, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2))
SDL_PROC(void, glRotated, (GLdouble angle, GLdouble x, GLdouble y, GLdouble z))
SDL_PROC(void, glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
SDL_PROC(void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height))
SDL_PROC(void, glShadeModel, (GLenum mode))
SDL_PROC(void, glTexCoord2f, (GLfloat s, GLfloat t))
SDL_PROC(void, glTexEnvf, (GLenum target, GLenum pname, GLfloat param))
SDL_PROC(void, glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels))
SDL_PROC(void, glTexParameteri, (GLenum target, GLenum pname, GLint param))
SDL_PROC(void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels))
SDL_PROC(void, glTranslatef, (GLfloat x, GLfloat y, GLfloat z))
SDL_PROC(void, glVertex2f, (GLfloat x, GLfloat y))
SDL_PROC(void, glVertex3fv, (const GLfloat * v))
SDL_PROC(void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height))
//SDL_PROC_UNUSED
SDL_PROC(GLboolean, glAreTexturesResident, (GLsizei, const GLuint *, GLboolean *))
SDL_PROC(GLboolean, glIsEnabled, (GLenum cap))
SDL_PROC(GLboolean, glIsList, (GLuint list))
SDL_PROC(GLboolean, glIsTexture, (GLuint texture))
SDL_PROC(GLint, glRenderMode, (GLenum mode))
SDL_PROC(GLuint, glGenLists, (GLsizei range))
SDL_PROC(void, glAccum, (GLenum, GLfloat))
SDL_PROC(void, glAlphaFunc, (GLenum, GLclampf))
SDL_PROC(void, glArrayElement, (GLint))
SDL_PROC(void, glBitmap, (GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, const GLubyte *))
SDL_PROC(void, glCallList, (GLuint))
SDL_PROC(void, glCallLists, (GLsizei, GLenum, const GLvoid *))
SDL_PROC(void, glClearAccum, (GLfloat, GLfloat, GLfloat, GLfloat))
//SDL_PROC(void, glClearDepth, (GLclampd))
SDL_PROC(void, glClearIndex, (GLfloat))
SDL_PROC(void, glClearStencil, (GLint))
//SDL_PROC(void, glClipPlane, (GLenum, const GLdouble *))
SDL_PROC(void, glColor3b, (GLbyte, GLbyte, GLbyte))
SDL_PROC(void, glColor3bv, (const GLbyte *))
//SDL_PROC(void, glColor3d, (GLdouble, GLdouble, GLdouble))
//SDL_PROC(void, glColor3dv, (const GLdouble *))
SDL_PROC(void, glColor3i, (GLint, GLint, GLint))
SDL_PROC(void, glColor3iv, (const GLint *))
SDL_PROC(void, glColor3s, (GLshort, GLshort, GLshort))
SDL_PROC(void, glColor3sv, (const GLshort *))
SDL_PROC(void, glColor3ub, (GLubyte, GLubyte, GLubyte))
SDL_PROC(void, glColor3ubv, (const GLubyte *))
SDL_PROC(void, glColor3ui, (GLuint, GLuint, GLuint))
SDL_PROC(void, glColor3uiv, (const GLuint *))
SDL_PROC(void, glColor3us, (GLushort, GLushort, GLushort))
SDL_PROC(void, glColor3usv, (const GLushort *))
SDL_PROC(void, glColor4b, (GLbyte, GLbyte, GLbyte, GLbyte))
SDL_PROC(void, glColor4bv, (const GLbyte *))
//SDL_PROC(void, glColor4d, (GLdouble, GLdouble, GLdouble, GLdouble))
//SDL_PROC(void, glColor4dv, (const GLdouble *))
SDL_PROC(void, glColor4fv, (const GLfloat *))
SDL_PROC(void, glColor4i, (GLint, GLint, GLint, GLint))
SDL_PROC(void, glColor4iv, (const GLint *))
SDL_PROC(void, glColor4s, (GLshort, GLshort, GLshort, GLshort))
SDL_PROC(void, glColor4sv, (const GLshort *))
SDL_PROC(void, glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
SDL_PROC(void, glColor4ubv, (const GLubyte * v))
SDL_PROC(void, glColor4ui, (GLuint red, GLuint green, GLuint blue, GLuint alpha))
SDL_PROC(void, glColor4uiv, (const GLuint * v))
SDL_PROC(void, glColor4us, (GLushort red, GLushort green, GLushort blue, GLushort alpha))
SDL_PROC(void, glColor4usv, (const GLushort * v))
SDL_PROC(void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
SDL_PROC(void, glColorMaterial, (GLenum face, GLenum mode))
SDL_PROC(void, glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer))
SDL_PROC(void, glCopyPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type))
SDL_PROC(void, glCopyTexImage1D, (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border))
SDL_PROC(void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
SDL_PROC(void, glCopyTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width))
SDL_PROC(void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
SDL_PROC(void, glCullFace, (GLenum mode))
SDL_PROC(void, glDeleteLists, (GLuint list, GLsizei range))
SDL_PROC(void, glDepthMask, (GLboolean flag))
//SDL_PROC(void, glDepthRange, (GLclampd zNear, GLclampd zFar))
SDL_PROC(void, glDisableClientState, (GLenum array))
SDL_PROC(void, glDrawArrays, (GLenum mode, GLint first, GLsizei count))
SDL_PROC(void, glDrawBuffer, (GLenum mode))
SDL_PROC(void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices))
SDL_PROC(void, glEdgeFlag, (GLboolean flag))
SDL_PROC(void, glEdgeFlagPointer, (GLsizei stride, const GLvoid * pointer))
SDL_PROC(void, glEdgeFlagv, (const GLboolean * flag))
SDL_PROC(void, glEnableClientState, (GLenum array))
SDL_PROC(void, glEndList, (void))
//SDL_PROC(void, glEvalCoord1d, (GLdouble u))
//SDL_PROC(void, glEvalCoord1dv, (const GLdouble * u))
SDL_PROC(void, glEvalCoord1f, (GLfloat u))
SDL_PROC(void, glEvalCoord1fv, (const GLfloat * u))
//SDL_PROC(void, glEvalCoord2d, (GLdouble u, GLdouble v))
//SDL_PROC(void, glEvalCoord2dv, (const GLdouble * u))
SDL_PROC(void, glEvalCoord2f, (GLfloat u, GLfloat v))
SDL_PROC(void, glEvalCoord2fv, (const GLfloat * u))
SDL_PROC(void, glEvalMesh1, (GLenum mode, GLint i1, GLint i2))
SDL_PROC(void, glEvalMesh2, (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2))
SDL_PROC(void, glEvalPoint1, (GLint i))
SDL_PROC(void, glEvalPoint2, (GLint i, GLint j))
SDL_PROC(void, glFeedbackBuffer, (GLsizei size, GLenum type, GLfloat * buffer))
SDL_PROC(void, glFinish, (void))
SDL_PROC(void, glFlush, (void))
SDL_PROC(void, glFogf, (GLenum pname, GLfloat param))
SDL_PROC(void, glFogfv, (GLenum pname, const GLfloat * params))
SDL_PROC(void, glFogi, (GLenum pname, GLint param))
SDL_PROC(void, glFogiv, (GLenum pname, const GLint * params))
SDL_PROC(void, glFrontFace, (GLenum mode))
//SDL_PROC(void, glFrustum, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
SDL_PROC(void, glGetBooleanv, (GLenum pname, GLboolean * params))
//SDL_PROC(void, glGetClipPlane, (GLenum plane, GLdouble * equation))
//SDL_PROC(void, glGetDoublev, (GLenum pname, GLdouble * params))
SDL_PROC(void, glGetFloatv, (GLenum pname, GLfloat * params))
SDL_PROC(void, glGetLightfv, (GLenum light, GLenum pname, GLfloat * params))
SDL_PROC(void, glGetLightiv, (GLenum light, GLenum pname, GLint * params))
//SDL_PROC(void, glGetMapdv, (GLenum target, GLenum query, GLdouble * v))
SDL_PROC(void, glGetMapfv, (GLenum target, GLenum query, GLfloat * v))
SDL_PROC(void, glGetMapiv, (GLenum target, GLenum query, GLint * v))
SDL_PROC(void, glGetMaterialfv, (GLenum face, GLenum pname, GLfloat * params))
SDL_PROC(void, glGetMaterialiv, (GLenum face, GLenum pname, GLint * params))
SDL_PROC(void, glGetPixelMapfv, (GLenum map, GLfloat * values))
SDL_PROC(void, glGetPixelMapuiv, (GLenum map, GLuint * values))
SDL_PROC(void, glGetPixelMapusv, (GLenum map, GLushort * values))
SDL_PROC(void, glGetPolygonStipple, (GLubyte * mask))
SDL_PROC(void, glGetTexEnvfv, (GLenum target, GLenum pname, GLfloat * params))
SDL_PROC(void, glGetTexEnviv, (GLenum target, GLenum pname, GLint * params))
//SDL_PROC(void, glGetTexGendv, (GLenum coord, GLenum pname, GLdouble * params))
SDL_PROC(void, glGetTexGenfv, (GLenum coord, GLenum pname, GLfloat * params))
SDL_PROC(void, glGetTexGeniv, (GLenum coord, GLenum pname, GLint * params))
SDL_PROC(void, glGetTexImage, (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels))
SDL_PROC(void, glGetTexLevelParameterfv, (GLenum target, GLint level, GLenum pname, GLfloat * params))
SDL_PROC(void, glGetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint * params))
SDL_PROC(void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat * params))
SDL_PROC(void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint * params))
SDL_PROC(void, glHint, (GLenum target, GLenum mode))
SDL_PROC(void, glIndexMask, (GLuint mask))
SDL_PROC(void, glIndexPointer, (GLenum type, GLsizei stride, const GLvoid * pointer))
//SDL_PROC(void, glIndexd, (GLdouble c))
//SDL_PROC(void, glIndexdv, (const GLdouble * c))
SDL_PROC(void, glIndexf, (GLfloat c))
SDL_PROC(void, glIndexfv, (const GLfloat * c))
SDL_PROC(void, glIndexi, (GLint c))
SDL_PROC(void, glIndexiv, (const GLint * c))
SDL_PROC(void, glIndexs, (GLshort c))
SDL_PROC(void, glIndexsv, (const GLshort * c))
SDL_PROC(void, glIndexub, (GLubyte c))
SDL_PROC(void, glIndexubv, (const GLubyte * c))
SDL_PROC(void, glInitNames, (void))
SDL_PROC(void, glInterleavedArrays, (GLenum format, GLsizei stride, const GLvoid * pointer))
SDL_PROC(void, glLightModelf, (GLenum pname, GLfloat param))
SDL_PROC(void, glLightModelfv, (GLenum pname, const GLfloat * params))
SDL_PROC(void, glLightModeli, (GLenum pname, GLint param))
SDL_PROC(void, glLightModeliv, (GLenum pname, const GLint * params))
SDL_PROC(void, glLightf, (GLenum light, GLenum pname, GLfloat param))
SDL_PROC(void, glLightfv, (GLenum light, GLenum pname, const GLfloat * params))
SDL_PROC(void, glLighti, (GLenum light, GLenum pname, GLint param))
SDL_PROC(void, glLightiv, (GLenum light, GLenum pname, const GLint * params))
SDL_PROC(void, glLineStipple, (GLint factor, GLushort pattern))
SDL_PROC(void, glListBase, (GLuint base))
//SDL_PROC(void, glLoadMatrixd, (const GLdouble * m))
SDL_PROC(void, glLoadMatrixf, (const GLfloat * m))
SDL_PROC(void, glLoadName, (GLuint name))
SDL_PROC(void, glLogicOp, (GLenum opcode))
//SDL_PROC(void, glMap1d, (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points))
SDL_PROC(void, glMap1f, (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points))
//SDL_PROC(void, glMap2d, (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points))
SDL_PROC(void, glMap2f, (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points))
//SDL_PROC(void, glMapGrid1d, (GLint un, GLdouble u1, GLdouble u2))
SDL_PROC(void, glMapGrid1f, (GLint un, GLfloat u1, GLfloat u2))
//SDL_PROC(void, glMapGrid2d, (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2))
SDL_PROC(void, glMapGrid2f, (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2))
SDL_PROC(void, glMaterialf, (GLenum face, GLenum pname, GLfloat param))
SDL_PROC(void, glMaterialfv, (GLenum face, GLenum pname, const GLfloat * params))
SDL_PROC(void, glMateriali, (GLenum face, GLenum pname, GLint param))
SDL_PROC(void, glMaterialiv, (GLenum face, GLenum pname, const GLint * params))
//SDL_PROC(void, glMultMatrixd, (const GLdouble * m))
SDL_PROC(void, glMultMatrixf, (const GLfloat * m))
SDL_PROC(void, glNewList, (GLuint list, GLenum mode))
SDL_PROC(void, glNormal3b, (GLbyte nx, GLbyte ny, GLbyte nz))
SDL_PROC(void, glNormal3bv, (const GLbyte * v))
//SDL_PROC(void, glNormal3d, (GLdouble nx, GLdouble ny, GLdouble nz))
//SDL_PROC(void, glNormal3dv, (const GLdouble * v))
SDL_PROC(void, glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz))
SDL_PROC(void, glNormal3fv, (const GLfloat * v))
SDL_PROC(void, glNormal3i, (GLint nx, GLint ny, GLint nz))
SDL_PROC(void, glNormal3iv, (const GLint * v))
SDL_PROC(void, glNormal3s, (GLshort nx, GLshort ny, GLshort nz))
SDL_PROC(void, glNormal3sv, (const GLshort * v))
SDL_PROC(void, glNormalPointer, (GLenum type, GLsizei stride, const GLvoid * pointer))
SDL_PROC(void, glPassThrough, (GLfloat token))
SDL_PROC(void, glPixelMapfv, (GLenum map, GLsizei mapsize, const GLfloat * values))
SDL_PROC(void, glPixelMapuiv, (GLenum map, GLsizei mapsize, const GLuint * values))
SDL_PROC(void, glPixelMapusv, (GLenum map, GLsizei mapsize, const GLushort * values))
SDL_PROC(void, glPixelStoref, (GLenum pname, GLfloat param))
SDL_PROC(void, glPixelTransferf, (GLenum pname, GLfloat param))
SDL_PROC(void, glPixelTransferi, (GLenum pname, GLint param))
SDL_PROC(void, glPixelZoom, (GLfloat xfactor, GLfloat yfactor))
SDL_PROC(void, glPolygonMode, (GLenum face, GLenum mode))
SDL_PROC(void, glPolygonOffset, (GLfloat factor, GLfloat units))
SDL_PROC(void, glPolygonStipple, (const GLubyte * mask))
SDL_PROC(void, glPopAttrib, (void))
SDL_PROC(void, glPopClientAttrib, (void))
SDL_PROC(void, glPopName, (void))
SDL_PROC(void, glPrioritizeTextures, (GLsizei n, const GLuint * textures, const GLclampf * priorities))
SDL_PROC(void, glPushAttrib, (GLbitfield mask))
SDL_PROC(void, glPushClientAttrib, (GLbitfield mask))
SDL_PROC(void, glPushName, (GLuint name))
//SDL_PROC(void, glRasterPos2d, (GLdouble x, GLdouble y))
//SDL_PROC(void, glRasterPos2dv, (const GLdouble * v))
SDL_PROC(void, glRasterPos2f, (GLfloat x, GLfloat y))
SDL_PROC(void, glRasterPos2fv, (const GLfloat * v))
SDL_PROC(void, glRasterPos2iv, (const GLint * v))
SDL_PROC(void, glRasterPos2s, (GLshort x, GLshort y))
SDL_PROC(void, glRasterPos2sv, (const GLshort * v))
//SDL_PROC(void, glRasterPos3d, (GLdouble x, GLdouble y, GLdouble z))
//SDL_PROC(void, glRasterPos3dv, (const GLdouble * v))
SDL_PROC(void, glRasterPos3f, (GLfloat x, GLfloat y, GLfloat z))
SDL_PROC(void, glRasterPos3fv, (const GLfloat * v))
SDL_PROC(void, glRasterPos3i, (GLint x, GLint y, GLint z))
SDL_PROC(void, glRasterPos3iv, (const GLint * v))
SDL_PROC(void, glRasterPos3s, (GLshort x, GLshort y, GLshort z))
SDL_PROC(void, glRasterPos3sv, (const GLshort * v))
//SDL_PROC(void, glRasterPos4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w))
//SDL_PROC(void, glRasterPos4dv, (const GLdouble * v))
SDL_PROC(void, glRasterPos4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w))
SDL_PROC(void, glRasterPos4fv, (const GLfloat * v))
SDL_PROC(void, glRasterPos4i, (GLint x, GLint y, GLint z, GLint w))
SDL_PROC(void, glRasterPos4iv, (const GLint * v))
SDL_PROC(void, glRasterPos4s, (GLshort x, GLshort y, GLshort z, GLshort w))
SDL_PROC(void, glRasterPos4sv, (const GLshort * v))
//SDL_PROC(void, glRectd, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2))
//SDL_PROC(void, glRectdv, (const GLdouble * v1, const GLdouble * v2))
SDL_PROC(void, glRectfv, (const GLfloat * v1, const GLfloat * v2))
SDL_PROC(void, glRecti, (GLint x1, GLint y1, GLint x2, GLint y2))
SDL_PROC(void, glRectiv, (const GLint * v1, const GLint * v2))
SDL_PROC(void, glRects, (GLshort x1, GLshort y1, GLshort x2, GLshort y2))
SDL_PROC(void, glRectsv, (const GLshort * v1, const GLshort * v2))
//SDL_PROC(void, glScaled, (GLdouble x, GLdouble y, GLdouble z))
SDL_PROC(void, glScalef, (GLfloat x, GLfloat y, GLfloat z))
SDL_PROC(void, glSelectBuffer, (GLsizei size, GLuint * buffer))
SDL_PROC(void, glStencilFunc, (GLenum func, GLint ref, GLuint mask))
SDL_PROC(void, glStencilMask, (GLuint mask))
SDL_PROC(void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass))
//SDL_PROC(void, glTexCoord1d, (GLdouble s))
//SDL_PROC(void, glTexCoord1dv, (const GLdouble * v))
SDL_PROC(void, glTexCoord1f, (GLfloat s))
SDL_PROC(void, glTexCoord1fv, (const GLfloat * v))
SDL_PROC(void, glTexCoord1i, (GLint s))
SDL_PROC(void, glTexCoord1iv, (const GLint * v))
SDL_PROC(void, glTexCoord1s, (GLshort s))
SDL_PROC(void, glTexCoord1sv, (const GLshort * v))
//SDL_PROC(void, glTexCoord2d, (GLdouble s, GLdouble t))
//SDL_PROC(void, glTexCoord2dv, (const GLdouble * v))
SDL_PROC(void, glTexCoord2fv, (const GLfloat * v))
SDL_PROC(void, glTexCoord2i, (GLint s, GLint t))
SDL_PROC(void, glTexCoord2iv, (const GLint * v))
SDL_PROC(void, glTexCoord2s, (GLshort s, GLshort t))
SDL_PROC(void, glTexCoord2sv, (const GLshort * v))
//SDL_PROC(void, glTexCoord3d, (GLdouble s, GLdouble t, GLdouble r))
//SDL_PROC(void, glTexCoord3dv, (const GLdouble * v))
SDL_PROC(void, glTexCoord3f, (GLfloat s, GLfloat t, GLfloat r))
SDL_PROC(void, glTexCoord3fv, (const GLfloat * v))
SDL_PROC(void, glTexCoord3i, (GLint s, GLint t, GLint r))
SDL_PROC(void, glTexCoord3iv, (const GLint * v))
SDL_PROC(void, glTexCoord3s, (GLshort s, GLshort t, GLshort r))
SDL_PROC(void, glTexCoord3sv, (const GLshort * v))
//SDL_PROC(void, glTexCoord4d, (GLdouble s, GLdouble t, GLdouble r, GLdouble q))
//SDL_PROC(void, glTexCoord4dv, (const GLdouble * v))
SDL_PROC(void, glTexCoord4f, (GLfloat s, GLfloat t, GLfloat r, GLfloat q))
//SDL_PROC(void, glTexCoord4fv, (const GLfloat * v))
SDL_PROC(void, glTexCoord4i, (GLint s, GLint t, GLint r, GLint q))
SDL_PROC(void, glTexCoord4iv, (const GLint * v))
SDL_PROC(void, glTexCoord4s, (GLshort s, GLshort t, GLshort r, GLshort q))
SDL_PROC(void, glTexCoord4sv, (const GLshort * v))
SDL_PROC(void, glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer))
SDL_PROC(void, glTexEnvfv, (GLenum target, GLenum pname, const GLfloat * params))
SDL_PROC(void, glTexEnvi, (GLenum target, GLenum pname, GLint param))
SDL_PROC(void, glTexEnviv, (GLenum target, GLenum pname, const GLint * params))
//SDL_PROC(void, glTexGend, (GLenum coord, GLenum pname, GLdouble param))
//SDL_PROC(void, glTexGendv, (GLenum coord, GLenum pname, const GLdouble * params))
SDL_PROC(void, glTexGenf, (GLenum coord, GLenum pname, GLfloat param))
SDL_PROC(void, glTexGenfv, (GLenum coord, GLenum pname, const GLfloat * params))
SDL_PROC(void, glTexGeni, (GLenum coord, GLenum pname, GLint param))
SDL_PROC(void, glTexGeniv, (GLenum coord, GLenum pname, const GLint * params))
SDL_PROC(void, glTexImage1D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels))
SDL_PROC(void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param))
SDL_PROC(void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat * params))
SDL_PROC(void, glTexParameteriv, (GLenum target, GLenum pname, const GLint * params))
SDL_PROC(void, glTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels))
//SDL_PROC(void, glTranslated, (GLdouble x, GLdouble y, GLdouble z))
//SDL_PROC(void, glVertex2d, (GLdouble x, GLdouble y))
//SDL_PROC(void, glVertex2dv, (const GLdouble * v))
SDL_PROC(void, glVertex2fv, (const GLfloat * v))
SDL_PROC(void, glVertex2i, (GLint x, GLint y))
SDL_PROC(void, glVertex2iv, (const GLint * v))
SDL_PROC(void, glVertex2s, (GLshort x, GLshort y))
SDL_PROC(void, glVertex2sv, (const GLshort * v))
//SDL_PROC(void, glVertex3d, (GLdouble x, GLdouble y, GLdouble z))
//SDL_PROC(void, glVertex3dv, (const GLdouble * v))
SDL_PROC(void, glVertex3f, (GLfloat x, GLfloat y, GLfloat z))
SDL_PROC(void, glVertex3i, (GLint x, GLint y, GLint z))
SDL_PROC(void, glVertex3iv, (const GLint * v))
SDL_PROC(void, glVertex3s, (GLshort x, GLshort y, GLshort z))
SDL_PROC(void, glVertex3sv, (const GLshort * v))
//SDL_PROC(void, glVertex4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w))
//SDL_PROC(void, glVertex4dv, (const GLdouble * v))
SDL_PROC(void, glVertex4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w))
SDL_PROC(void, glVertex4fv, (const GLfloat * v))
SDL_PROC(void, glVertex4i, (GLint x, GLint y, GLint z, GLint w))
SDL_PROC(void, glVertex4iv, (const GLint * v))
SDL_PROC(void, glVertex4s, (GLshort x, GLshort y, GLshort z, GLshort w))
SDL_PROC(void, glVertex4sv, (const GLshort * v))
SDL_PROC(void, glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer))

//db0 added OpenGLes
SDL_PROC(GLboolean, glIsBuffer,(GLuint buffer))
SDL_PROC(GLboolean, glIsFramebuffer,(GLuint framebuffer))
SDL_PROC(GLboolean, glIsProgram,(GLuint program))
SDL_PROC(GLboolean, glIsRenderbuffer,(GLuint renderbuffer))
SDL_PROC(GLboolean, glIsShader,(GLuint shader))
SDL_PROC(GLenum, glCheckFramebufferStatus, (GLenum))
SDL_PROC(GLint, glGetAttribLocation, (GLuint, const char*))
SDL_PROC(GLint, glGetUniformLocation, (GLuint, const char *))
SDL_PROC(GLuint, glCreateProgram, (void))
SDL_PROC(GLuint, glCreateShader, (GLenum))
SDL_PROC(void, glActiveTexture, (GLenum))
SDL_PROC(void, glAttachShader, (GLuint, GLuint))
SDL_PROC(void, glBindAttribLocation, (GLuint, GLuint, const char *))
SDL_PROC(void, glBindBuffer,(GLenum target,  GLuint buffer))
SDL_PROC(void, glBindFramebuffer, (GLenum, GLuint))
SDL_PROC(void, glBindRenderbuffer,(GLenum target,  GLuint renderbuffer))
SDL_PROC(void, glBlendColor,(GLclampf red,  GLclampf green,  GLclampf blue,  GLclampf alpha))
SDL_PROC(void, glBlendEquation,(GLenum mode))
SDL_PROC(void, glBlendEquationSeparate,(GLenum modeRGB,  GLenum modeAlpha))
SDL_PROC(void, glBufferData,(GLenum target,  GLsizeiptr size,  const GLvoid * data,  GLenum usage))
SDL_PROC(void, glBufferSubData,(GLenum target,  GLintptr offset,  GLsizeiptr size,  const GLvoid * data))
SDL_PROC(void, glClearDepthf,(GLclampf depth))
SDL_PROC(void, glCompileShader, (GLuint))
SDL_PROC(void, glCompressedTexImage2D,(GLenum target,  GLint level,  GLenum internalformat,  GLsizei width,  GLsizei height,  GLint border,  GLsizei imageSize,  const GLvoid * data))
SDL_PROC(void, glCompressedTexSubImage2D,(GLenum target,  GLint level,  GLint xoffset,  GLint yoffset,  GLsizei width,  GLsizei height,  GLenum format,  GLsizei imageSize,  const GLvoid * data)) 
SDL_PROC(void, glDeleteBuffers,(GLsizei n,  const GLuint * buffers))
SDL_PROC(void, glDeleteFramebuffers, (GLsizei, const GLuint *))
SDL_PROC(void, glDeleteProgram, (GLuint))
SDL_PROC(void, glDeleteRenderbuffers,(GLsizei n,  const GLuint * renderbuffers))
SDL_PROC(void, glDeleteShader, (GLuint))
SDL_PROC(void, glDepthRangef,(GLclampf nearVal,  GLclampf farVal))
SDL_PROC(void, glDetachShader,(GLuint program,  GLuint shader))
SDL_PROC(void, glDisableVertexAttribArray, (GLuint))
SDL_PROC(void, glEnableVertexAttribArray, (GLuint))
SDL_PROC(void, glFramebufferRenderbuffer,(GLenum target,  GLenum attachment,  GLenum renderbuffertarget,  GLuint renderbuffer))
SDL_PROC(void, glFramebufferTexture2D, (GLenum, GLenum, GLenum, GLuint, GLint))
SDL_PROC(void, glGenBuffers,(GLsizei n,  GLuint * buffers))
SDL_PROC(void, glGenFramebuffers, (GLsizei, GLuint *))
SDL_PROC(void, glGenRenderbuffers,(GLsizei n,  GLuint * renderbuffers))
SDL_PROC(void, glGenerateMipmap,(GLenum target))
SDL_PROC(void, glGetActiveAttrib,(GLuint program,  GLuint index,  GLsizei bufSize,  GLsizei *length,  GLint *size,  GLenum *type,  char *name))
SDL_PROC(void, glGetActiveUniform,(GLuint program,  GLuint index,  GLsizei bufSize,  GLsizei *length,  GLint *size,  GLenum *type,  char *name))
SDL_PROC(void, glGetAttachedShaders,(GLuint program,  GLsizei maxCount,  GLsizei *count,  GLuint *shaders))
SDL_PROC(void, glGetBufferParameteriv,(GLenum target,  GLenum value,  GLint * data))
SDL_PROC(void, glGetFramebufferAttachmentParameteriv,(GLenum target,  GLenum attachment,  GLenum pname,  GLint * params))
SDL_PROC(void, glGetProgramInfoLog,(GLuint program,  GLsizei maxLength,  GLsizei *length,  char *infoLog)) 
SDL_PROC(void, glGetProgramiv, (GLuint, GLenum, GLint *))
SDL_PROC(void, glGetRenderbufferParameteriv,(GLenum target,  GLenum pname,  GLint * params))
SDL_PROC(void, glGetShaderInfoLog, (GLuint, GLsizei, GLsizei *, char *))
SDL_PROC(void, glGetShaderPrecisionFormat,(GLenum shaderType,  GLenum precisionType,  GLint *range,  GLint *precision))
SDL_PROC(void, glGetShaderSource,(GLuint shader,  GLsizei bufSize,  GLsizei *length,  char *source))
SDL_PROC(void, glGetShaderiv, (GLuint, GLenum, GLint *))
SDL_PROC(void, glGetUniformfv,(GLuint program,  GLint location,  GLfloat *params)) 
SDL_PROC(void, glGetUniformiv,(GLuint program,  GLint location,  GLint *params))
SDL_PROC(void, glGetVertexAttribPointerv,(GLuint index,  GLenum pname,  GLvoid **pointer))
SDL_PROC(void, glGetVertexAttribfv,(GLuint index,  GLenum pname,  GLfloat *params))
SDL_PROC(void, glGetVertexAttribiv,(GLuint index,  GLenum pname,  GLint *params))
SDL_PROC(void, glLinkProgram, (GLuint))
SDL_PROC(void, glReleaseShaderCompiler,(void))
SDL_PROC(void, glRenderbufferStorage,(GLenum target,  GLenum internalformat,  GLsizei width,  GLsizei height))
SDL_PROC(void, glSampleCoverage,(GLclampf value,  GLboolean invert)) 
SDL_PROC(void, glShaderBinary, (GLsizei, const GLuint *, GLenum, const void *, GLsizei))
SDL_PROC(void, glShaderSource, (GLuint, GLsizei, const char **, const GLint *))
SDL_PROC(void, glStencilFuncSeparate,(GLenum face,  GLenum func,  GLint ref,  GLuint mask))
SDL_PROC(void, glStencilMaskSeparate,(GLenum face,  GLuint mask))
SDL_PROC(void, glStencilOpSeparate,(GLenum face,  GLenum sfail,  GLenum dpfail,  GLenum dppass))
SDL_PROC(void, glUniform1f,(GLint location,  GLfloat v0))
SDL_PROC(void, glUniform1fv,(GLint location,  GLsizei count,  const GLfloat *value))
SDL_PROC(void, glUniform1i, (GLint, GLint))
SDL_PROC(void, glUniform1iv,(GLint location,  GLsizei count,  const GLint *value))
SDL_PROC(void, glUniform2f,(GLint location,  GLfloat v0,  GLfloat v1))
SDL_PROC(void, glUniform2fv,(GLint location,  GLsizei count,  const GLfloat *value))
SDL_PROC(void, glUniform2i,(GLint location,  GLint v0,  GLint v1))
SDL_PROC(void, glUniform2iv,(GLint location,  GLsizei count,  const GLint *value))
SDL_PROC(void, glUniform3f,(GLint location,  GLfloat v0,  GLfloat v1,  GLfloat v2))
SDL_PROC(void, glUniform3fv,(GLint location,  GLsizei count,  const GLfloat *value))
SDL_PROC(void, glUniform3i,(GLint location,  GLint v0,  GLint v1,  GLint v2))
SDL_PROC(void, glUniform3iv,(GLint location,  GLsizei count,  const GLint *value))
SDL_PROC(void, glUniform4f, (GLint, GLfloat, GLfloat, GLfloat, GLfloat))
SDL_PROC(void, glUniform4fv,(GLint location,  GLsizei count,  const GLfloat *value))
SDL_PROC(void, glUniform4i,(GLint location,  GLint v0,  GLint v1,  GLint v2,  GLint v3))
SDL_PROC(void, glUniform4iv,(GLint location,  GLsizei count,  const GLint *value))
SDL_PROC(void, glUniformMatrix2fv,(GLint location,  GLsizei count,  GLboolean transpose,  const GLfloat *value))
SDL_PROC(void, glUniformMatrix3fv,(GLint location,  GLsizei count,  GLboolean transpose,  const GLfloat *value))
SDL_PROC(void, glUniformMatrix4fv, (GLint, GLsizei, GLboolean, const GLfloat *))
SDL_PROC(void, glUseProgram, (GLuint))
SDL_PROC(void, glValidateProgram,(GLuint program))
SDL_PROC(void, glVertexAttrib1f,(GLuint index,  GLfloat v0))
SDL_PROC(void, glVertexAttrib1fv,(GLuint index,  const GLfloat *v))
SDL_PROC(void, glVertexAttrib2f,(GLuint index,  GLfloat v0,  GLfloat v1))
SDL_PROC(void, glVertexAttrib2fv,(GLuint index,  const GLfloat *v))
SDL_PROC(void, glVertexAttrib3f,(GLuint index,  GLfloat v0,  GLfloat v1,  GLfloat v2))
SDL_PROC(void, glVertexAttrib3fv,(GLuint index,  const GLfloat *v))
SDL_PROC(void, glVertexAttrib4f,(GLuint index,  GLfloat v0,  GLfloat v1,  GLfloat v2,  GLfloat v3))
SDL_PROC(void, glVertexAttrib4fv,(GLuint index,  const GLfloat *v))
SDL_PROC(void, glVertexAttribPointer, (GLuint, GLint, GLenum, GLboolean, GLsizei, const void *))
/* vi: set ts=4 sw=4 expandtab: */
